import mysql.connector
conn=mysql.connector.connect(host='localhost',user='root',password='Simran12@')
mycursor=conn.cursor()
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(101,'Mathematics',3);")
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(102,'History;,4);")
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(103,'Computer Science',3);")
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(104,'Literature',3);")
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(105,'Chemistry',4);")
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(106,'Physics',4);")
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(107,'Economics',3);")
mycursor.execute("insert into ASSIGNMENT1.createdb.course values(108,'Biology',4);")
conn.commit()
conn.close()
